// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZEZm4ncQCvM0im_GMhqhk8ZpvCjuEL-4',
    appId: '1:398821978800:web:e3e66143c730dad48c4175',
    messagingSenderId: '398821978800',
    projectId: 'plantty-42bda',
    authDomain: 'plantty-42bda.firebaseapp.com',
    storageBucket: 'plantty-42bda.firebasestorage.app',
    measurementId: 'G-43DSKK8YS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx4iuI8wTi55IyOmxjprmjAt1uuZEwsK4',
    appId: '1:398821978800:android:8e126f5d3793b68a8c4175',
    messagingSenderId: '398821978800',
    projectId: 'plantty-42bda',
    storageBucket: 'plantty-42bda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnOVH-JRQVIxu0bQ0JYlU93Xu8OuqVn8',
    appId: '1:398821978800:ios:fcedb982b4cd37ae8c4175',
    messagingSenderId: '398821978800',
    projectId: 'plantty-42bda',
    storageBucket: 'plantty-42bda.firebasestorage.app',
    iosBundleId: 'com.example.myBluetoothApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGnOVH-JRQVIxu0bQ0JYlU93Xu8OuqVn8',
    appId: '1:398821978800:ios:fcedb982b4cd37ae8c4175',
    messagingSenderId: '398821978800',
    projectId: 'plantty-42bda',
    storageBucket: 'plantty-42bda.firebasestorage.app',
    iosBundleId: 'com.example.myBluetoothApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZEZm4ncQCvM0im_GMhqhk8ZpvCjuEL-4',
    appId: '1:398821978800:web:0ad8e53f6ea2411a8c4175',
    messagingSenderId: '398821978800',
    projectId: 'plantty-42bda',
    authDomain: 'plantty-42bda.firebaseapp.com',
    storageBucket: 'plantty-42bda.firebasestorage.app',
    measurementId: 'G-QXR10ZCRS7',
  );
}
